resource_group_name          = "travis-function-rg"
location                     = "South Central US"
storage_account_name         = "travisfunctionsa"
log_analytics_workspace_name = "travis-function-la"
app_insights_name            = "travis-function-ai"
app_service_plan_name        = "travis-function-sp"
function_app_name            = "travis-function-testing-app"
